# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 100)
        self.horizontalWidget = QtWidgets.QWidget(Dialog)
        self.horizontalWidget.setGeometry(QtCore.QRect(0, 30, 600, 31))
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout_3.setContentsMargins(11, 4, 11, 2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.genre = QtWidgets.QComboBox(self.horizontalWidget)
        self.genre.setObjectName("genre")
        self.horizontalLayout_3.addWidget(self.genre)
        self.year_spinbox = QtWidgets.QSpinBox(self.horizontalWidget)
        self.year_spinbox.setMinimum(1895)
        self.year_spinbox.setMaximum(2021)
        self.year_spinbox.setProperty("value", 1895)
        self.year_spinbox.setObjectName("year_spinbox")
        self.horizontalLayout_3.addWidget(self.year_spinbox)
        self.time_spinbox = QtWidgets.QSpinBox(self.horizontalWidget)
        self.time_spinbox.setMaximum(250)
        self.time_spinbox.setObjectName("time_spinbox")
        self.horizontalLayout_3.addWidget(self.time_spinbox)
        self.title = QtWidgets.QLineEdit(self.horizontalWidget)
        self.title.setObjectName("title")
        self.horizontalLayout_3.addWidget(self.title)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(504, 65, 85, 25))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(11, 10, 73, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(91, 10, 31, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(121, 10, 71, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(280, 10, 191, 20))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Ок"))
        self.label.setText(_translate("Dialog", "Жанры"))
        self.label_2.setText(_translate("Dialog", "Год "))
        self.label_3.setText(_translate("Dialog", "Время"))
        self.label_4.setText(_translate("Dialog", "Название"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
